#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car2GoTripsView
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Car2Go")]
	public partial class Car2GoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public Car2GoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Car2GoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Car2GoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Car2GoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Car2GoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Car2GoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CityLookup> CityLookups
		{
			get
			{
				return this.GetTable<CityLookup>();
			}
		}
		
		public System.Data.Linq.Table<PercentileCoordDate> PercentileCoordDates
		{
			get
			{
				return this.GetTable<PercentileCoordDate>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FindTripEnds", IsComposable=true)]
		public IQueryable<FindTripEndsResult> FindTripEnds([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripStart", DbType="DateTime")] System.Nullable<System.DateTime> tripStart, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripEnd", DbType="DateTime")] System.Nullable<System.DateTime> tripEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityIndex", DbType="Int")] System.Nullable<int> cityIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartLatMin", DbType="Float")] System.Nullable<double> startLatMin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartLatMax", DbType="Float")] System.Nullable<double> startLatMax, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartLonMin", DbType="Float")] System.Nullable<double> startLonMin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartLonMax", DbType="Float")] System.Nullable<double> startLonMax)
		{
			return this.CreateMethodCallQuery<FindTripEndsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tripStart, tripEnd, cityIndex, startLatMin, startLatMax, startLonMin, startLonMax);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FindTripStarts", IsComposable=true)]
		public IQueryable<FindTripStartsResult> FindTripStarts([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripStart", DbType="DateTime")] System.Nullable<System.DateTime> tripStart, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripEnd", DbType="DateTime")] System.Nullable<System.DateTime> tripEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityIndex", DbType="Int")] System.Nullable<int> cityIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartLatMin", DbType="Float")] System.Nullable<double> startLatMin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartLatMax", DbType="Float")] System.Nullable<double> startLatMax, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartLonMin", DbType="Float")] System.Nullable<double> startLonMin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartLonMax", DbType="Float")] System.Nullable<double> startLonMax)
		{
			return this.CreateMethodCallQuery<FindTripStartsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tripStart, tripEnd, cityIndex, startLatMin, startLatMax, startLonMin, startLonMax);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CityLookup")]
	public partial class CityLookup
	{
		
		private string _City;
		
		private System.Nullable<long> _CityIndex;
		
		public CityLookup()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityIndex", DbType="BigInt")]
		public System.Nullable<long> CityIndex
		{
			get
			{
				return this._CityIndex;
			}
			set
			{
				if ((this._CityIndex != value))
				{
					this._CityIndex = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PercentileCoordDate")]
	public partial class PercentileCoordDate
	{
		
		private System.Nullable<double> _P90_Lat;
		
		private System.Nullable<double> _P95_Lat;
		
		private double _P10_Lat;
		
		private double _P05_Lat;
		
		private System.Nullable<double> _P90_Lon;
		
		private System.Nullable<double> _P95_Lon;
		
		private double _P10_Lon;
		
		private double _P05_Lon;
		
		private System.Nullable<long> _cityIndex;
		
		public PercentileCoordDate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P90_Lat", DbType="Float")]
		public System.Nullable<double> P90_Lat
		{
			get
			{
				return this._P90_Lat;
			}
			set
			{
				if ((this._P90_Lat != value))
				{
					this._P90_Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P95_Lat", DbType="Float")]
		public System.Nullable<double> P95_Lat
		{
			get
			{
				return this._P95_Lat;
			}
			set
			{
				if ((this._P95_Lat != value))
				{
					this._P95_Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P10_Lat", DbType="Float NOT NULL")]
		public double P10_Lat
		{
			get
			{
				return this._P10_Lat;
			}
			set
			{
				if ((this._P10_Lat != value))
				{
					this._P10_Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P05_Lat", DbType="Float NOT NULL")]
		public double P05_Lat
		{
			get
			{
				return this._P05_Lat;
			}
			set
			{
				if ((this._P05_Lat != value))
				{
					this._P05_Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P90_Lon", DbType="Float")]
		public System.Nullable<double> P90_Lon
		{
			get
			{
				return this._P90_Lon;
			}
			set
			{
				if ((this._P90_Lon != value))
				{
					this._P90_Lon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P95_Lon", DbType="Float")]
		public System.Nullable<double> P95_Lon
		{
			get
			{
				return this._P95_Lon;
			}
			set
			{
				if ((this._P95_Lon != value))
				{
					this._P95_Lon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P10_Lon", DbType="Float NOT NULL")]
		public double P10_Lon
		{
			get
			{
				return this._P10_Lon;
			}
			set
			{
				if ((this._P10_Lon != value))
				{
					this._P10_Lon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P05_Lon", DbType="Float NOT NULL")]
		public double P05_Lon
		{
			get
			{
				return this._P05_Lon;
			}
			set
			{
				if ((this._P05_Lon != value))
				{
					this._P05_Lon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityIndex", DbType="BigInt")]
		public System.Nullable<long> cityIndex
		{
			get
			{
				return this._cityIndex;
			}
			set
			{
				if ((this._cityIndex != value))
				{
					this._cityIndex = value;
				}
			}
		}
	}
	
	public partial class FindTripEndsResult
	{
		
		private System.Nullable<int> _COUNT;
		
		private System.Nullable<int> _Lat;
		
		private System.Nullable<int> _Lon;
		
		private System.Nullable<int> _MinDuration;
		
		private System.Nullable<int> _MaxDuration;
		
		private System.Nullable<int> _AverageDuration;
		
		public FindTripEndsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT", DbType="Int")]
		public System.Nullable<int> COUNT
		{
			get
			{
				return this._COUNT;
			}
			set
			{
				if ((this._COUNT != value))
				{
					this._COUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Int")]
		public System.Nullable<int> Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this._Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lon", DbType="Int")]
		public System.Nullable<int> Lon
		{
			get
			{
				return this._Lon;
			}
			set
			{
				if ((this._Lon != value))
				{
					this._Lon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinDuration", DbType="Int")]
		public System.Nullable<int> MinDuration
		{
			get
			{
				return this._MinDuration;
			}
			set
			{
				if ((this._MinDuration != value))
				{
					this._MinDuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxDuration", DbType="Int")]
		public System.Nullable<int> MaxDuration
		{
			get
			{
				return this._MaxDuration;
			}
			set
			{
				if ((this._MaxDuration != value))
				{
					this._MaxDuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AverageDuration", DbType="Int")]
		public System.Nullable<int> AverageDuration
		{
			get
			{
				return this._AverageDuration;
			}
			set
			{
				if ((this._AverageDuration != value))
				{
					this._AverageDuration = value;
				}
			}
		}
	}
	
	public partial class FindTripStartsResult
	{
		
		private System.Nullable<int> _COUNT;
		
		private System.Nullable<int> _Lat;
		
		private System.Nullable<int> _Lon;
		
		private System.Nullable<int> _MinDuration;
		
		private System.Nullable<int> _MaxDuration;
		
		private System.Nullable<int> _AverageDuration;
		
		public FindTripStartsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT", DbType="Int")]
		public System.Nullable<int> COUNT
		{
			get
			{
				return this._COUNT;
			}
			set
			{
				if ((this._COUNT != value))
				{
					this._COUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Int")]
		public System.Nullable<int> Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this._Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lon", DbType="Int")]
		public System.Nullable<int> Lon
		{
			get
			{
				return this._Lon;
			}
			set
			{
				if ((this._Lon != value))
				{
					this._Lon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinDuration", DbType="Int")]
		public System.Nullable<int> MinDuration
		{
			get
			{
				return this._MinDuration;
			}
			set
			{
				if ((this._MinDuration != value))
				{
					this._MinDuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxDuration", DbType="Int")]
		public System.Nullable<int> MaxDuration
		{
			get
			{
				return this._MaxDuration;
			}
			set
			{
				if ((this._MaxDuration != value))
				{
					this._MaxDuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AverageDuration", DbType="Int")]
		public System.Nullable<int> AverageDuration
		{
			get
			{
				return this._AverageDuration;
			}
			set
			{
				if ((this._AverageDuration != value))
				{
					this._AverageDuration = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
